// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://fxkjcrgzyogxhosjvzby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4a2pjcmd6eW9neGhvc2p2emJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjIyNTMsImV4cCI6MjA3MzgzODI1M30.Pm5uWvko5H-UtVDZ33jn0YYB0IP3S6V0w6CuI7X3EZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
